services:
    starbase80:
        image: jordanroher/starbase-80
        ports:
            - 3000:4173
        environment:
            - TITLE=松果
            - LOGO=/logo.png
            - HEADER= false
        volumes:
            - ./config.json:/app/src/config/config.json
            - ./public/favicon.ico:/app/public/favicon.ico
            - ./public/logo.png:/app/public/logo.png
            - ./public/icons:/app/public/icons